# Generated by Django 5.2.5 on 2026-08-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0012_remove_legacy_ebay_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into the internal admin platform.",
                verbose_name="staff status",
            ),
        ),
    ]
